import { sendEmail } from './../mailer';
export const PRODUCTS = [
    {
        title:'peach',
        description:'PROD1',
        price:3.5,
        quantity:50,
        creator:'5ed9eaaeb327df2174cbd8cd',
        sector:'FAV'
    },
    {
        title:'cherry',
        description:'PROD2',
        price:3,
        quantity:50,
        creator:'5ed9eaaeb327df2174cbd8cd',
        sector:'FAV'
    },
    {
        title:'beef',
        description:'PROD3',
        price:15,
        quantity:50,
        creator:'5ed9eaaeb327df2174cbd8c8',
        sector:'MEAT'
    },
    {
        title:'chicken',
        description:'PROD4',
        price:7,
        quantity:50,
        creator:'5ed9eaaeb327df2174cbd8c8',
        sector:'MEAT'
    },
    {
        title:'lobster',
        description:'PROD5',
        price:20,
        quantity:50,
        creator:'5ed9eaaeb327df2174cbd8ca',
        sector:'SEAFOOD'
    },
    {
        title:'fish',
        description:'PROD6',
        price:7,
        quantity:50,
        creator:'5ed9eaaeb327df2174cbd8ca',
        sector:'SEAFOOD'
    },
    {
        title:'cottagecheese',
        description:'PROD7',
        price:4,
        quantity:50,
        creator:'5ed9eaaeb327df2174cbd8cc',
        sector:'DAIRY'
    },
    {
        title:'swiss cheese',
        description:'PROD8',
        price:6.4,
        quantity:50,
        creator:'5ed9eaaeb327df2174cbd8cc',
        sector:'DAIRY'
    },
    {
        title:'lam milk',
        description:'PROD9',
        price:8,
        quantity:50,
        creator:'5ed9eaaeb327df2174cbd8cc',
        sector:'DAIRY'
    },
    {
        title:'cucamber',
        description:'PROD10',
        price:1.5,
        quantity:50,
        creator:'5ed9eaaeb327df2174cbd8cd',
        sector:'FAV'
    }
]